# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from with_jwt import Authentication_pb2 as Authentication__pb2


class AuthenticationStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Login = channel.unary_unary(
        '/authentication.Authentication/Login',
        request_serializer=Authentication__pb2.LoginRequest.SerializeToString,
        response_deserializer=Authentication__pb2.Response.FromString,
        )
    self.Signup = channel.unary_unary(
        '/authentication.Authentication/Signup',
        request_serializer=Authentication__pb2.SignupRequest.SerializeToString,
        response_deserializer=Authentication__pb2.Response.FromString,
        )
    self.Query = channel.unary_unary(
        '/authentication.Authentication/Query',
        request_serializer=Authentication__pb2.QueryRequest.SerializeToString,
        response_deserializer=Authentication__pb2.QueryResponse.FromString,
        )


class AuthenticationServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Login(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Signup(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Query(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AuthenticationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Login': grpc.unary_unary_rpc_method_handler(
          servicer.Login,
          request_deserializer=Authentication__pb2.LoginRequest.FromString,
          response_serializer=Authentication__pb2.Response.SerializeToString,
      ),
      'Signup': grpc.unary_unary_rpc_method_handler(
          servicer.Signup,
          request_deserializer=Authentication__pb2.SignupRequest.FromString,
          response_serializer=Authentication__pb2.Response.SerializeToString,
      ),
      'Query': grpc.unary_unary_rpc_method_handler(
          servicer.Query,
          request_deserializer=Authentication__pb2.QueryRequest.FromString,
          response_serializer=Authentication__pb2.QueryResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'authentication.Authentication', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
